version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
  build:
    commands:
      # Run script to setup the CodeBuild server with the necessary AWS profile
      - pip install jq
      - creds=$(aws sts get-session-token)

      - AWS_PROFILE = "ecommerce-item-manager"
      - AWS_ACCESS_KEY_ID=$(echo $creds | jq '.Credentials.AccessKeyId')
      - AWS_SECRET_ACCESS_KEY=$(echo $creds | jq '.Credentials.SecretAccessKey')
      - AWS_SESSION_TOKEN=$(echo $creds | jq '.Credentials.SessionToken')

      - aws configure --profile $AWS_PROFILE set region "us-east-1"
      - aws configure --profile $AWS_PROFILE set output "json"
      - aws configure --profile $AWS_PROFILE set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
      - aws configure --profile $AWS_PROFILE set aws_access_key_id "$AWS_ACCESS_KEY_ID"
      - aws configure --profile $AWS_PROFILE set aws_session_token "$AWS_SESSION_TOKEN"

      # Generate the underlying cloudformation template that is generated by serverless
      - npm run package

      # copy the template from .serverless (where serverless outputs it) to the root template.json
      - cp ./.serverless/cloudformation-template-update-stack.json template-export.json

  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - template-export.json
    - template-configuration.json
